### ISSUE TITLE
Trash Tracker should detect which town you're in

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#100]
We'll need to display trash drop off locations or allow the user to geo-locate a roadside trash drop depending on what town they are standing in.  

We'll use GPS and polygon data on each town together with the point-in-polygon-extended npm library to find the user's town.

https://www.npmjs.com/package/point-in-polygon-extended

Teresa is getting us Trash Drop locations and info on which town allow roadside.

**Comment by smaraf** [comment]
From Jenny B.:

- here’s the link for towns w/2016 ACS pop, https://api.censusreporter.org/1.0/data/download/latest?table_ids=B01003&geo_ids=04000US50,060%7C04000US50&format=geojson
- if you want to use e911 points for your address locator, this will be a better bet (official vt town boundaries): https://opendata.arcgis.com/datasets/0e4a5d2d58ac40bf87cd8aa950138ae8_39.geojson
- use turf.js to determine if a point is in a polygon.  Turf has an inside() method that looks super easy to use.  Turf handles geojson so there'll no need to convert the data.  http://turfjs.org/

**Comment by smaraf** [comment]
Pushed initial code for town detection to branch [Trash-Tracker](https://github.com/johnneed/GreenUpVermont/tree/Trash-Tracker)

**Comment by smaraf** [comment]
This ended up being easier than I thought. Proper data retrieval is still yet to be implemented but here's an overview of what I have so far in terms of UI:

For a town where roadside drop-off is permitted we display a message and we then display existing trash drops, the ability to show collected drops and create a road-side drop. 

![screenshot_20180305-175850](https://user-images.githubusercontent.com/1213709/37004790-a1e748e8-209f-11e8-98a7-1806d691c8e3.png)

For a town where roadside drop-off is not permitted we display a message as well as the designated drop off location and address. We then hide the 'Show Collected Drops' toggle, existing trash drops and do not offer the ability to create a toad-side drop. We show a blue pin on the map indicating where the drop off location is.

![screenshot_20180305-175959](https://user-images.githubusercontent.com/1213709/37004865-eebe6db8-209f-11e8-8e34-b904d9efa934.png)

@johnneed Is this pretty much what you had in mind for this feature?

Outstanding work is:

- implement proper data retrieval from the database so that we have the ability to tweak data on the spot without rebuilding the app
- import data into firebase from [spreadsheet](https://drive.google.com/file/d/1IWAYqCCMcdKfdlOTMpN2SXAhSQqIxhTv/view)
- find out what the coordinates are for all addresses
- Nice to have: add the ability to handle multiple drop off locations - right now the data does not indicate this is needed but it would be fairly easy to do just in case it will be needed

**Comment by smaraf** [comment]
PR: https://github.com/johnneed/GreenUpVermont/pull/145

**Comment by smaraf** [comment]
PR merged to master, closing this issue
