### ISSUE TITLE
Updated user profile name not reflected in team members list.

### ISSUE THREAD

**Issue by jmargolisvt** [johnneed/GreenUpVermont#119]
When I go to Menu -> My Profile, I see that the name field is pre-populated with data from the google login.  But when I change it, it's not reflected in the Team Member Editor area.  Not sure if this problem is limited to Google logins or not.

**Comment by jmargolisvt** [comment]
It seems that Profiles and Team Members contain different data in Firebase.  @johnneed can you share a bit about how this user data is supposed to work together?

**Comment by johnneed** [comment]
The main difference between TeamMember and Profile is the member status.   The profile is used when creating adding a new TeamMember.     You'll notice a lot of repeated data.  This is not only common in document databases, but recommended.   The real for the repetition is because of security rules.  Only a users can edit their own profiles, but other people can add or delete team members.   All the security rules aren't in place right now.

**Comment by johnneed** [comment]
Oh and if you're invited to join a team , but not yet registered, the teamMember will be created using different data.
