### ISSUE TITLE
Create Trash Drop doesn't work

### ISSUE THREAD

**Issue by kmeyersvt** [johnneed/GreenUpVermont#131]
Testing on Android
1. Tapped Trash icon.
2. Zoomed in and tapped on the map at Saint Michaels
3. Tapped Create Trash Drop
4. Did not check any boxes or make any changes on the screen.
5. Tapped Mark This Spot.
6. My green pin did not appear on Saint Michaels

Tried it again tapping the Large Object checkbox and it also didn't mark it with a green pin.

**Comment by johnneed** [comment]
You can only create a trash drop at your current location.   We should probably add a note about this.

**Comment by doub1ejack** [comment]
Can we disable zooming/panning on the map?  

I'm not sure what the real use-case would be for marking trash at locations other than your current one.  I suppose we're assuming that we have users who are so anxious to use the app that they never forget to mark trash as soon as they drop off a bag – someone could easily forget to mark it until they've walked elsewhere or even driven home.

**Comment by kmeyersvt** [comment]
What is the use case for the trash drop? Are the Green Up committees in each town going to use it to figure out where to pick up trash?

I think that we do need to allow setting pins in other locations for exactly the reason that you stated - "Oops, I didn't indicate where my trash bags were, let me do that now. From home, miles away."

**Comment by johnneed** [comment]
I wouldn't want to disable zoom since the trash tracker is also meant to be used by folks picking up trash as well as folks looking for drop off locations.

**Comment by kmeyersvt** [comment]
Tested in the new version on Android and it still doesn't save my Trash Drop. I see other peoples' drops, but I just added one for 100 bags with large object and tires and I don't see it. There was already a pin for one bag in Winooski where I am.

**Comment by smaraf** [comment]
@kmeyersvt  it's likely that your pin is hidden behind the existing one and that's why it appears as if it's not created - I have observed this behavior while testing as well. An easy way to verify is to collect the existing pin (tap on the marker, tap on the callout then click collect trash) and then try to add it again.

There's an existing [issue](https://github.com/johnneed/GreenUpVermont/issues/105) for the fact that you can only create a trash drop at your current location and there isn't an option to select the exact spot on the map for it. If this becomes a priority it wouldn't be a huge lift to implement.

I agree with @johnneed that we probably don't want to disable the zoom.

**Comment by kmeyersvt** [comment]
I tried it from home  instead of work and it does work on Android.  I can see my pin with the proper details.

**Comment by smaraf** [comment]
I'm closing this issue based on the comments above.
