### ISSUE TITLE
Cannot Invite from Contacts

### ISSUE THREAD

**Issue by kmeyersvt** [johnneed/GreenUpVermont#137]
The list populates in batches (I DO have a lot of contacts) but even when fully loaded, if I tap a name or the checkbox, the check appears briefly and then goes away. I cannot invite anyone from my contacts list.

**Comment by doub1ejack** [comment]
Checked that this is working on my iPhone.  Saw John pull up his contact list on his phone also.

**Comment by kmeyersvt** [comment]
The contact list populates, but could you check one and choose Invite at the bottom of the list? That's what didn't work.

**Comment by jmargolisvt** [comment]
I see this bug on Android too.  Can't really debug it on my Android phone, and can't get contacts to import in Xcode, so not sure how to debug, and not sure if it's limited to Android.  When I check a contact on Android, it unchecks it about a second or two later, so that's a good first place to look.

**Comment by johnneed** [comment]
Issue is with the CheckBox control.  It only works on iOS.  There is a RN native control, but it only works on Android.   I'll add a check to render the correct control depending on the OS.
