### ISSUE TITLE
Clean up town trash bag finder data

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#193]
We have weird characters, bad spacing, bad line breaks and other issues  in the town data. 

View the Trash Bag finder screen and you'll see the issues.

**Comment by jmargolisvt** [comment]
I just cleaned up the db a little.  No commit needed.  Let's just make sure we take this cleaned up copy of the town data into prod @johnneed .

**Comment by smaraf** [comment]
@jmargolisvt  @johnneed  The source of truth for the town data is in this spreadsheet: https://docs.google.com/spreadsheets/d/14nKyYeIGsLJ1syWhjchnMQsCMACfMCaoOzYc2coukiU/edit?usp=drive_web&ouid=105811502439750701904

We're expecting more changes from Teresa as well to this dataset. The Firebase data is expected to be blown away and re-imported from the spreadsheet. We should probably do the clean-up in the spreadsheet as well otherwise, it will be lost with the next import.
