### ISSUE TITLE
Add ability to mark trash drops as "Collected"

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#39]
PIns should be able to marked as picked-up.
Only pin owners should be able to delete a pin.
Pins that have been marked "collected" should not appear on the map by default.
There should be a toggle to view collected drops.
Anyone should be able to mark a drop as collected, but that person's id should be recorded.

**Comment by johnneed** [comment]
We'll need this so we can properly collect metrics on amount of trash collected

**Comment by johnneed** [comment]
It would also be nice if we could live report the number of bags dropped and collected.

**Comment by smaraf** [comment]
One thing that I noticed while working in this and it might be nice to have is to add the ability to select the location where the trash is dropped. Right now the current location of the device is used but in my mind, this can cause issues due to the (im)precision of the GPS or perhaps the user updating the tracker after they walked away from the exact location where they left the trash. 

The Uber app has the same ability where by default the current location of the device is selected but there's also the ability to drag the location around to another location. This is probably not MVP but something nice to have. I can create a separate issue for it if it sounds like something we would want to have. 

@johnneed What do you think?

**Comment by johnneed** [comment]
I would say yes to everything you're saying, including the part where it's not MVP.

If you've been following the chatter on Slack, you already know that there are lots of new requirements for trash-tracker regarding determining if you can drop your bags on the road, depending on what town you're in.

This is a major feature that we need to address first.   I'll be adding those issues soon. 

Also I think you're becoming our map expert.

**Comment by smaraf** [comment]
I created https://github.com/johnneed/GreenUpVermont/issues/105 for the nice to have work described above.

@johnneed  I don't mind taking the map work as I learned a lot working on some of the issues so far. Feel free to assign it to me.

**Comment by smaraf** [comment]
PR was merged to master and I verified it still works as expected. Closing.
