### ISSUE TITLE
Add a Where to Get Bags screen.

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#65]
Maybe we should have a town selector with info about each town
Link to this from menu screen.

**Comment by smaraf** [comment]
I will to the data import into firebase for this task while working on the data import on https://github.com/johnneed/GreenUpVermont/issues/100 since both have the same origin.  If this task is still open once I'm done with https://github.com/johnneed/GreenUpVermont/issues/100 I can grab this one next. If anyone else grabs it before then, let's coordinate on the data piece.
